### ISSUE TITLE
compile error on macOS

### ISSUE THREAD

**Issue by palindrom615** [rindeal/Amalgamate#2]
Hi,

I am having trouble with compiling this repository on MacOS.

Importing `cocoa/cocoa.h`(https://github.com/rindeal/Amalgamate/blob/master/juce_core_amalgam.cpp#L222) without linking objective-c causes compile error like:

```
In file included from juce_core_amalgam.cpp:222:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/Cocoa.framework/Headers/Cocoa.h:12:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/Foundation.framework/Headers/Foundation.h:8:
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSObjCRuntime.h:492:1: error: expected unqualified-id
@class NSString, Protocol;
^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSObjCRuntime.h:494:9: error: unknown type name 'NSString'
typedef NSString * NSExceptionName NS_EXTENSIBLE_STRING_ENUM;
        ^
```

**Comment by palindrom615** [comment]
I guess that this guy faced the same issue.

https://forum.juce.com/t/unknown-type-name-nsstring-on-new-mac-os-build/32085

**Comment by rindeal** [comment]
JUCE just needs to be compiled as Objective-C++. This is easily acomplished just by renaming/linking from `.cpp` to `.mm`. Anyway, I implemented the switching logic into the Makefile, updated JUCE to the latest version and also added CI tests for MacOS. Cheers.
